version: '3'

networks:
  catadoct.net:
    driver: bridge

services:
  php:
    image: 'canals/php:latest'
    depends_on:
      - db.catadoct
    networks:
      - catadoct.net

  db.catadoct:
    image: "postgres:latest"
    env_file:
      - db.env
    ports:
      - '11111:5432'
    volumes:
      - ./sql:/var/sql'
    networks:
      - catadoct.net

  adminer:
    image: adminer
    env_file: ./db.env
    command: php -S 0.0.0.0:8080 -t /var/www/html
    ports:
      - '11112:8080'
    networks:
      - catadoct.net