version: '3'

networks:
  catadoct.net:
    driver: bridge

services:
  php:
    image: 'canals/php:8.2'
    depends_on:
      - db.catadoct
    volumes:
      - ./:/var/www/html
    networks:
      - catadoct.net
    ports:
      - '11110:80'

  db.catadoct:
    image: "postgres:latest"
    env_file:
      - db.env
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - '11111:5432'
    networks:
      - catadoct.net

  adminer:
    image: adminer
    ports:
      - '11112:8080'
    networks:
      - catadoct.net